name: Sync OAS to ReadMe
on:
  push:
    branches:
      - master
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
          oas-file-path: './openapi.v2.yaml'
          api-version: 'v1.0.0'
           
          # OPTIONAL CONFIG, use if necessary
          # oas-file-path: './swagger.json'
          # api-version: 'v1.0.0'
