name: Sync Markdown Docs to ReadMe!
on:
  push:
   branches:
     - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout steps
        uses: actions/checkout@v2.3.4
      - name: Update Docs
        run: npx rdme docs ./Merchant-Guide-v2/ --key ${{ secrets.README_API_KEY }} --version v1.0
